ankitpokhrel/jira-cli

cmd/jira/issue.go, cmd/jira/sprint.go, internal/view/issue.go, internal/view/issue_test.go
Trim columns by default in plain mode so that it won't overflow the screen. A new `--no-truncate` option is available to display all available fields in plain mode.
EG:
```
$ jira issue --plain
$ jira issue --plain --no-truncate
```
=> feat: Add --no-truncate flag

cmd/jira/init.go, cmd/jira/root.go, internal/config/generator.go, internal/config/generator_test.go
This PR moves config to `$HOME/.config` from `$HOME` as recommended by the [XDG spec](https://wiki.archlinux.org/index.php/XDG_Base_Directory#Specification). We don't comply with the full spec though.
=> chore: Refactor config as per XDG spec

internal/cmd/issue/issue.go, internal/cmd/issue/move/move.go, pkg/jira/testdata/transitions.json, pkg/jira/transition.go, pkg/jira/transition_test.go, pkg/jira/types.go
```
$ jira issue move -h
Move transitions an issue from one state to another.
Usage:
jira issue move ISSUE_KEY STATE [flags]
Aliases:
move, transition
Flags:
-h, --help   help for move
Global Flags:
-c, --config string    Config file (default is $HOME/.config/jira/.jira.yml)
--debug            Turn on debug output
-p, --project string   Jira project to look into (defaults to value from $HOME/.config/jira/.jira.yml)
```
=> feat: Initial move/transition cmd impl

.gitignore, internal/cmd/epic/create/create.go, internal/cmd/epic/epic.go, internal/cmd/issue/create/create.go, pkg/jira/create.go, pkg/jira/create_test.go, pkg/jira/types.go
Epic name is required when creating epic, but Jira uses a custom field for an epic name which is different on each installation. Instead of fetching this dynamic field every time it is good to store it in the config since it is the same for projects on the same Jira instance. This PR implementation assumes that the epic field name is stored in `$HOME/.config/jira/.jira.yml` as `epic.field`.
TODO: Add epic field name in config during initialization.
=> feat: Epic create cmd

README.md, internal/cmd/sprint/list/list.go, internal/cmdutil/utils.go, internal/cmdutil/utils_test.go, internal/query/sprint.go, internal/query/sprint_test.go, internal/view/helper.go, internal/view/helper_test.go, internal/view/issue.go, internal/view/issues.go, internal/view/sprint.go, pkg/jira/sprint.go
This PR adds `--current`, `--prev` and `--next` flags for quick sprint navigation
```sh
$ jira sprint list --current
$ jira sprint list --prev
$ jira sprint list --next
```
=> feat: Add quick sprint flags

internal/cmd/root/root.go, internal/cmdutil/utils.go, internal/cmdutil/utils_test.go, internal/config/generator.go
From the [XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):
> $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.
Requires config regeneration.
=> feat: Respect XDG_CONFIG_HOME env

README.md, internal/cmd/epic/add/add.go, internal/cmd/epic/epic.go, pkg/jira/client.go, pkg/jira/client_test.go, pkg/jira/epic.go, pkg/jira/epic_test.go
```sh
$ jira epic add -h
Add issues to an epic.
USAGE
jira epic add EPIC_KEY ISSUE_1 [...ISSUE_N] [flags]
FLAGS
-h, --help   help for add
INHERITED FLAGS
-c, --config string    Config file (default is $HOME/.jira/.config.yml)
--debug            Turn on debug output
-p, --project string   Jira project to look into (defaults to value from $HOME/.jira/.config.yml)
ARGUMENTS
EPIC_KEY		Epic to which you want to assign issues to, eg: EPIC-1
ISSUE_1 [...ISSUE_N]	Key of the issues to add to an epic (max 50 issues at once)
EXAMPLES
$ jira epic add EPIC_KEY ISSUE_1 ISSUE_2
LEARN MORE
Use 'jira <command> <subcommand> --help' for more information about a command.
```
```sh
$ jira epic add
$ jira epic add EPIC_KEY ISSUE_1 ISSUE_2
```
=> feat: Ability to add issues to the epic

internal/cmd/epic/add/add.go, internal/cmd/epic/epic.go, internal/cmd/epic/remove/remove.go, pkg/jira/epic.go, pkg/jira/epic_test.go
Main command `remove`, aliases `rm` and `unassign`.
```sh
$ jira epic remove ISSUE-1 ISSUE-2
$ jira epic rm ISSUE-1
$ jira epic unassign ISSUE-1 ISSUE-N
```
=> feat: Ability to unassign epic from issues

README.md, internal/cmd/issue/comment/add/add.go, internal/cmd/issue/comment/comment.go, internal/cmd/issue/issue.go, pkg/jira/issue.go, pkg/jira/issue_test.go
Only supports plain text comments at the moment.
```sh
$ jira issue comment add
$ jira issue comment add ISSUE-1 "My comment body"
$ jira issue comment add ISSUE-1 $'This comment has\n\nNew line'
```
=> feat: Ability to add comment

README.md, internal/cmd/epic/create/create.go, internal/cmd/issue/create/create.go, internal/cmdcommon/create.go, internal/cmdutil/utils.go
This PR adds an ability to load description from pre-defined template. It adds an option called `--template` that can be used to pass pre-defined templates. The template supports [Github flavored](https://github.github.com/gfm/) and/or [Jira flavored markdown](https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=all).
- Create issue using a pre-defined template. The template will be loaded to screen in interactive mode.
```sh
$ jira issue create -s"Testing Template 101" -tTask --template /path/to/template.tmpl
? Description <Received>
? What's next? Submit 
✓ Issue created
https://antiklabs.atlassian.net/browse/ANK-169
```
- Create issue directly using a pre-defined template.
```sh
$ jira issue create -s"Testing Template 101" -tTask --template ~/Desktop/desc.tmpl …
```
=> feat: Support template for description during issue creation

README.md, internal/cmd/issue/comment/add/add.go, internal/cmd/issue/create/create.go, pkg/jira/issue.go, pkg/jira/issue_test.go
This PR:
- Lets you write comments using Github/Jira flavored markdown.
- Provide support for templates when adding comments.
```sh
$ jira issue comment add ISSUE-1 --template /path/to/template.tmpl
$ jira issue comment add ISSUE-1 --template -
$ echo "Comment from stdin" | jira issue comment add ISSUE-1
```
=> feat: Support markdown and template when adding comments

cmd/jira/main.go, internal/cmd/root/root.go
Right now if the `JIRA_API_TOKEN` is not set, the command shows token error even before showing any help. It would be nice if we show help even though the the token is not set.
This PR makes some adjustment such that help is shown even if Jira token is not set. And, If the user proceeds to use commands other than help, token error is shown as before.
=> Show help even if token is not set

internal/cmd/root/root.go, internal/config/generator.go, pkg/jira/client.go
Fixes #95 
Debug mode now dumps all request and response details (except for the response body).
```sh
$ jira init --debug
REQUEST DETAILS
------------------------------------------------------------
GET /rest/api/3/myself HTTP/1.1
Host: example.atlassian.net
Authorization: Basic <token>
RESPONSE DETAILS
------------------------------------------------------------
HTTP/1.1 401 Unauthorized
Transfer-Encoding: chunked
Atl-Traceid: b21117d7a37cefa4
Cache-Control: no-transform
Connection: keep-alive
Content-Type: application/xml;charset=UTF-8
Date: Sat, 15 May 2021 11:35:38 GMT
Expect-Ct: report-uri="https://web-security-reports.services.atlassian.com/expect-ct-report/global-proxy", enforce, max-age=86400
Server: AtlassianProxy/1.19.3.1
Set-Cookie: …
```
=> Improve debug mode

internal/cmd/init/init.go, internal/cmdutil/utils.go, pkg/jira/board.go, pkg/jira/board_test.go, pkg/jira/client.go, pkg/jira/create.go, pkg/jira/create_test.go, pkg/jira/createmeta.go, pkg/jira/createmeta_test.go, pkg/jira/epic.go, pkg/jira/epic_test.go, pkg/jira/issue.go, pkg/jira/issue_test.go, pkg/jira/me.go, pkg/jira/me_test.go, pkg/jira/project.go, pkg/jira/project_test.go, pkg/jira/search.go, pkg/jira/search_test.go, pkg/jira/sprint.go, pkg/jira/sprint_test.go, pkg/jira/transition.go, pkg/jira/transition_test.go, pkg/jira/user.go, pkg/jira/user_test.go
This PR improves error reporting to include errors and warnings from Jira API response.
**Before**
```sh
$ jira issue list -tasdf -yasdf -rsdf
jira: Received unexpected response.
Please check the parameters you supplied and try again.
```
**After**
```sh
$ jira issue list -tasdf -yasdf -rsdf
Error:
- The value 'asdf' does not exist for the field 'type'.
- The value 'asdf' does not exist for the field 'priority'.
Warning:
- The value 'sdf' does not exist for the field 'reporter'.
jira: Received unexpected response '400 Bad Request'.
Please check the parameters you supplied and try again.
```
=> feat: Improve error reporting

internal/cmd/issue/create/create.go, internal/cmdcommon/create.go, internal/cmdutil/utils_test.go, pkg/jira/create.go
Jira issue create will now allow to create sub-tasks as well.
```sh
$ jira issue create -t"Sub-task" -PISSUE-X
```
=> feat: Allow to create sub-task

README.md, internal/cmd/issue/list/list.go, internal/query/issue.go, internal/query/issue_test.go, pkg/jql/jql.go, pkg/jql/jql_test.go
You can execute raw JQL within a given project context using `--jql/-q` option. For instance, the following command will list issues in current project whose summary has a word `cli`.
```sh
$ jira issue list -q "summary ~ cli"
```
=> feat: Support raw JQL

README.md, internal/cmd/issue/clone/clone.go, internal/cmd/issue/issue.go, pkg/jira/client.go, pkg/jira/client_test.go, pkg/jira/issue.go, pkg/jira/issue_test.go, pkg/jira/testdata/issue-2.json
The `clone` command lets you clone an issue. You can update fields like summary, priority, assignee, labels, and
components when cloning the issue. The command also allows you to replace a part of the string (case-sensitive)
in summary and description using `--replace/-H` option.
```sh
$ jira issue clone ISSUE-1
$ jira issue clone ISSUE-1 -s"Modified summary" -yHigh -a$(jira me)
$ jira issue clone ISSUE-1 -H"find me:replace with me"
```
=> feat: Add cmd to clone issue

internal/cmd/epic/add/add.go, internal/cmd/epic/remove/remove.go, internal/cmd/issue/assign/assign.go, internal/cmd/issue/clone/clone.go, internal/cmd/issue/comment/add/add.go, internal/cmd/issue/link/link.go, internal/cmd/issue/move/move.go, internal/cmd/issue/view/view.go, internal/cmd/open/open.go, internal/cmdutil/utils.go, internal/cmdutil/utils_test.go
This PR makes changes to append project context automatically to issue keys so that we can just use key numbers instead of typing full key. The change is applied to all commands that requires issue key. 
For instance:
```sh
$ jira epic add 11 12 13 14
```
Above command will expand to `jira epic add ISS-11 ISS-12 ISS-13 ISS-14` if current configured project key is `ISS`.
=> feat: Auto project context

.gitignore, .goreleaser.yml
This PR adds [goreleaser](https://goreleaser.com/) config to build binary for:
- macOS/darwin [amd64, arm64]
- linux [386, arm, amd64, arm64]
- windows [386, amd64]
=> build: Prepare for initial release

README.md, internal/cmd/issue/edit/edit.go, internal/cmd/issue/issue.go, pkg/jira/client.go, pkg/jira/client_test.go, pkg/jira/edit.go
This PR adds a command to edit issues.
```sh
$ jira issue edit ISSUE-1
```
```sh
Edit an issue in a given project with minimal information.
USAGE
jira issue edit ISSUE-KEY [flags]
FLAGS
-s, --summary string          Edit summary or title
-b, --body string             Edit description
-y, --priority string         Edit priority
-a, --assignee string         Edit assignee (email or display name)
-l, --label stringArray       Edit labels
-C, --component stringArray   Edit components
--web                     Open in web browser after successful update
--no-input                Disable prompt for non-required fields
-h, --help                    help for edit
INHERITED FLAGS
-c, --config string    Config file (default is $HOME/.jira/.config.yml)
--debug            Turn on debug output
-p, …
```
=> feat: Add cmd to edit issue

go.mod, go.sum
This prevents build errors in OSes where the module does not have support.
`../../pkg/mod/github.com/pkg/browser@v0.0.0-20210706143420-7d21f8c997e2/browser_unsupported.go:7:2: imported and not used: "os/exec"`
Related Issue: https://github.com/pkg/browser/issues/37
NOTE: Also a PR to support NetBSD in browser has been submitted https://github.com/pkg/browser/pull/39
=> Update browser module to latest.

go.mod, go.sum
Looks like https://github.com/pkg/browser/pull/39 got merged and now there should be native NetBSD support.
Updated the module to point to the latest.
Reference: Build fix was done in PR https://github.com/ankitpokhrel/jira-cli/pull/134
=> Update browser module - Adds NetBSD support.

README.md, internal/config/generator.go, pkg/jira/createmeta.go, pkg/jira/createmeta_test.go, pkg/jira/me.go, pkg/jira/me_test.go, pkg/jira/project.go, pkg/jira/project_test.go
This PR provides a base to test the tool in on-premise jira installation. It fixes `jira init` command to work with both cloud and local jira installations.
=> feat: Support init cmd for on-premise jira installation

internal/cmd/issue/clone/clone.go
If there is no description added when creating an issue, the `clone` command panics because `Description` field is returned as `nil` instead of empty string.
```sh
$ jira issue clone ISS-220
⠦ Fetching issue details... panic: interface conversion: interface {} is nil, not string
goroutine 1 [running]:
github.com/kmdpl/jira-cli/internal/cmd/issue/clone.(*cloneCmd).getActualCreateParams(0xc0005bfd28, 0xc0002500f0)
/Users/kmdpl/go/src/github.com/kmdpl/jira-cli/internal/cmd/issue/clone/clone.go:189 +0x4f1
github.com/kmdpl/jira-cli/internal/cmd/issue/clone.clone(0xc0005ef400, {0xc0004a2580, 0x1, 0x1})
/Users/kmdpl/go/src/github.com/kmdpl/jira-cli/internal/cmd/issue/clone/clone.go:70 +0x1c5
github.com/spf13/cobra.(*Command).execute(0xc0005ef400, {0xc0004a2560, 0x1, 0x1}) …
```
=> fix: Description can be nil in v2 version of the API

internal/cmd/issue/view/view.go, internal/view/issue.go, internal/view/issue_test.go, pkg/jira/issue.go
This PR adds basic support for view command when using on-premise jira installation. The description text is displayed as it is and might not look great in the CLI at the moment. This will be improved in the upcoming PRs.
=> feat: Basic support for view command for on-premise jira installation 

internal/view/issue.go, internal/view/issue_test.go, pkg/md/doc.go, pkg/md/jirawiki/parser.go, pkg/md/jirawiki/parser_test.go, pkg/md/md.go
This PR implements a multi-pass parser to convert [jirawiki or jira flavored markdown](https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=all) to a [commonmark markdown](https://spec.commonmark.org/current/). 
The conversion happens in 2 pass:
1. First pass simply fetches lines we are interested in from the input.
2. Second pass finds and mark the token + use replacements to prepare the markdown.
Not all of the jirawiki tags are supported at the moment.
<details><summary>Jira wiki markdown of the UI below</summary>
```
h1. This is the task heading
{quote}This is a subtitle in a blockquote
{quote}
*A list of tasks*
* Task 1
* Task 2
** Subtask 1
** Subtask 2
*** Subtask 2 item 1
* Task 3
* Task 4
{panel:title=Acceptance Criteria}
This *shit* should work as expected. …
```
=> feat: Implement jirawiki to markdown parser

internal/config/generator.go
Fix example URL spelling of Atlassian
=> Fix example URL spelling in generator.go

internal/view/project.go, internal/view/project_test.go, pkg/jira/issue.go, pkg/jira/project.go, pkg/jira/types.go
Jira cloud can have either a `classic` or a `next-gen` project. This PR adds a `TYPE` field when listing the project.
=> feat: Add type on project listing

internal/cmd/board/board.go, internal/cmd/epic/add/add.go, internal/cmd/epic/create/create.go, internal/cmd/epic/list/list.go, internal/cmd/epic/remove/remove.go, internal/cmd/issue/assign/assign.go, internal/cmd/issue/clone/clone.go, internal/cmd/issue/comment/add/add.go, internal/cmd/issue/create/create.go, internal/cmd/issue/edit/edit.go, internal/cmd/issue/link/link.go, internal/cmd/issue/list/list.go, internal/cmd/issue/move/move.go, internal/cmd/issue/view/view.go, internal/cmd/open/open.go, internal/cmd/root/root.go, internal/cmd/sprint/list/list.go, internal/config/generator.go
This change require regenerating the config file.
**Before**
```sh
project: ANK
```
**After**
```sh
project:
key: ANK
type: classic
```
Partially relates to #186
=> cfg!: Expand config to include project type

internal/cmd/epic/create/create.go, internal/config/generator.go, pkg/jira/epic.go, pkg/jira/types.go
This PR:
- Renames `epic.field` to `epic.name`
- Adds `epic.link` field
*Requires config regeneration.
=> cfg!: Rename field to name and add link field to epic

internal/cmd/issue/list/list.go, internal/query/issue.go, internal/query/issue_test.go
This PR adds filter by parent when fetching issues. This can be used to list sub-tasks in a story or epic issues in a next-gen project.
```sh
$ jira issue list -P ISS-10
```
=> feat: Allow to filter by parent

internal/view/helper.go
Link and key copying with `c` and `ctrl+k` is broken if key column is altered in the tui.
Related: #202 #199
=> fix(tui): Link/key copy is broken for altered key col

README.md, internal/cmd/sprint/add/add.go, internal/cmd/sprint/sprint.go, pkg/jira/sprint.go, pkg/jira/sprint_test.go
This PR adds a command to assign issues to the sprint.
```sh
$ jira sprint add
$ jira sprint add SPRINT_ID ISSUE-1 ISSUE-2
```
Fixes #183
=> feat: Cmd to add issues to sprint

go.mod, internal/view/helper.go, internal/view/helper_test.go, internal/view/issue.go, internal/view/issue_test.go, pkg/jira/types.go
`jira issue view` now displays linked issues if there is any.
This is how it looks in the screen.
**Dark mode (iterm2)**
**Light mode (macOS terminal)**
=> feat: Show linked issues when viewing

README.md, api/client.go, internal/cmd/issue/view/view.go, internal/view/epic.go, internal/view/issue.go, internal/view/issue_test.go, internal/view/issues.go, internal/view/sprint.go, pkg/jira/filter/doc.go, pkg/jira/filter/filter.go, pkg/jira/filter/filter_test.go, pkg/jira/filter/issue/num_comments.go, pkg/jira/issue.go
We can now use `--comments <limit>` filter to load `N` comments when viewing the issue.
```sh
// This will load 5 comments
$ jira issue view ISSUE-1 --comments 5
```
=> feat: Add an option to load N comments when viewing issue

.goreleaser.yml, Makefile, internal/version/version.go
Reproducible builds are good. https://reproducible-builds.org/
* edit `.goreleaser.yml` ldflags:
* change `GitCommit={{.Commit}}` to `GitCommit={{.FullCommit}}` because a
full hash is better than a short hash --- and the `Makefile` was already
using the full hash
* remove `BuildDate`, add `SourceDateEpoch={{.CommitTimestamp}}`
* edit `Makefile` build vars:
* change the `GIT_COMMIT` detection: if the worktree is dirty, then the sha1
is a "stash entry", else the sha1 is the current HEAD; allow envvar
override
* remove `build_date`, add `SOURCE_DATE_EPOCH` that defaults to the Unix
timestamp of the `GIT_COMMIT`; allow envvar override
* change `LDFLAGS` assignment from immediate (`:=`) to successive appends
(`+=`) such that we can accumulate envvar overrides from the `make` caller;
to the …
=> fix #243: reproducible builds

internal/version/version.go
edit `internal/version/version.go`:
* change `GitCommit` "poison" default value to the empty string
* change `SourceDate` to `CommitDate` and change its "poison" default value to
the empty string
=> fix #243: reproducible builds take 2

README.md, internal/version/default.go, internal/version/version.go
This PR adds a file that is compiled only for go1.12 or later. The main purpose is to initialize `version` from runtime information when user runs `go install github.com/ankitpokhrel/jira-cli/cmd/jira@latest`. Version is populated based on the latest build version.
```sh
(Version="v0.2.1-0.20220106190958-d362a5d3dedc", GitCommit="", CommitDate="", GoVersion="go1.16.6", Compiler="gc", Platform="linux/amd64")
```
=> build: Initialize version using runtime build info

Makefile
Turned out to be easy to fix #251 , it's just newline handling that has changed. It now works both with make 3.81 and 4.3:
```
$ rm ~/gocode/bin/golangci-lint
$ make lint
golangci/golangci-lint info checking GitHub for tag 'v1.43.0'
golangci/golangci-lint info found version: 1.43.0 for v1.43.0/darwin/amd64
golangci/golangci-lint info installed ~/gocode/bin/golangci-lint
golangci-lint run ./...
$ rm ~/gocode/bin/golangci-lint
$ gmake lint
golangci/golangci-lint info checking GitHub for tag 'v1.43.0'
golangci/golangci-lint info found version: 1.43.0 for v1.43.0/darwin/amd64
golangci/golangci-lint info installed ~/gocode/bin/golangci-lint
```
=> Fix Makefile compatiblity with Make 3.81

api/client.go, internal/cmd/init/init.go, internal/cmdutil/utils.go, internal/config/generator.go, pkg/jira/client.go
This PR adds an `--insecure` option in `init` cmd to skip TLS verification. This can be useful if the Jira server is using self-signed certificates.
Relates to: https://github.com/ankitpokhrel/jira-cli/discussions/271#discussioncomment-2091603
=> feat: Allow insecure TLS

internal/cmd/open/open.go
This PR adds `--no-browser` option to `open` cmd that allow us to skip opening destination URL in the browser.
=> feat: Add --no-browser option to open cmd

internal/cmd/board/board.go, internal/cmd/board/list/list.go, internal/cmd/project/list/list.go, internal/cmd/project/project.go
> BREAKING CHANGE
This PR moves boards and project listing to `list` subcommand. This will make them consistent with other commands and enable us to add additional features.
```sh
$ jira boards
$ jira projects
```
```sh
$ jira board list
$ jira project list
```
=> refactor!: Move boards and project list to subcommand

pkg/md/jirawiki/parser.go, pkg/md/jirawiki/parser_test.go
This PR fixes some issue with jira wiki parser.
1. Fixes panic on some older contents wrapped inside curly braces.
2. Fixes formatting issues with fenced code block if they are closed inline.
=> fix: Jira wiki parser

internal/cmd/sprint/list/list.go
This is a small fix to display correctly possible columns to be passed to List Sprint command as noted in the issue below:
https://github.com/ankitpokhrel/jira-cli/issues/263
=> Minor fix: display correctly columns in list sprint command help

internal/cmd/issue/create/create.go, internal/cmdcommon/create.go, internal/config/generator.go, internal/query/issue_test.go, internal/query/query.go, internal/query/sprint_test.go, pkg/jira/create.go, pkg/jira/createmeta.go, pkg/jira/createmeta_test.go, pkg/jira/customfield.go, pkg/jira/types.go
This PR adds initial support for custom fields on the issue creation. Relates to https://github.com/ankitpokhrel/jira-cli/discussions/222. Fixes #340.
Jira supports a wide variety of datatypes when creating a custom field. Out of all [formats mentioned in the Jira doc](https://developer.atlassian.com/cloud/jira/service-desk/rest/intro/#fieldformats), the implementation right now doesn't support `Cascading select custom field`, `Single-user picker custom field` and  `Multi-user picker custom field`. Support for these missing types will be added based on the request and the usecase.
Since we are already using the [createmeta endpoint](https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issues/#api-rest-api-2-issue-createmeta-get) to save metadata during `jira init` …
=> feat: Support custom fields on issue create

pkg/jira/edit.go
We can use minus `-` to remove labels when editing the issue.
```sh
$ jira issue edit 35 --label "-cmd" --label "-next" --label "prio"
```
=> feat: Allow removing labels on edit

internal/cmd/issue/create/create.go, internal/cmdutil/utils.go, internal/cmdutil/utils_test.go
Before, the code was assuming only one sub-task type existed (the
default). This would cause any issues filed with a custom sub-task type
to fail with the following error:
```
Error:
- Issue 'XXX-23668' must be of type 'Epic'.
jira: Received unexpected response '400 Bad Request'
```
because `jira.CreateRequest::SubtaskField` was not being set.
Fix by modifying `GetSubtaskHandle()` helper to look for exact matches
on sub-task types.
=> Support creating issues with custom subtask type

pkg/jira/edit.go
We can use minus `-` to remove fixVersions when editing the issue.
```sh
jira issue edit 35 --fix-version -v1.0 --fix-version v2.0
```
=> feat: Allow removing fixVersions on edit

internal/cmd/issue/edit/edit.go, pkg/jira/customfield.go, pkg/jira/edit.go
Related: #319 #375
Similar to issue create, we can use `--custom` flag to edit custom fields on edit.
```sh
jira issue edit 35 --custom story-points=3 --custom due-date="2022-03-10T14:39:00.000+1100" \
--custom note="A custom note" --custom platform=Windows,Linux --custom quarter=Q3 --custom tags=p1,q3,y2022
```
For multiple selection, we can use minus `-` to remove items
```sh
jira issue edit 35 --custom platform=-Windows,Linux --custom quarter=Q3 --custom tags=p1,-q3,y2022
```
=> feat: Support custom fields on issue edit

internal/cmd/init/init.go, internal/config/generator.go
Fixes #366
We can now use available flags to skip the prompt while generating the config.
```sh
$ jira init --installation cloud --server https://demo.atlassian.net --login user@example.com --project KEY --board "My Board Name"
```
Available flags
```sh
$ jira init -h
Init initializes jira configuration required for the tool to work properly.
USAGE
jira init [flags]
FLAGS
--installation string   Is this a 'cloud' or 'local' jira installation?
--server string         Link to your jira server
--login string          Jira login username or email based on your setup
--board string          Name of your default board in the project
--force                 Forcefully override existing config if it exists
--insecure              If set, the tool will skip TLS certificate verification.
This can …
```
=> feat: Jira init non-interactive

internal/cmd/issue/clone/clone.go
This PR adds a `--parent/-P` flag that will allow you to set parent when cloning a subtask. If parent is not set, the subtask will be added to the parent of the subtask being cloned.
=> fix: Subtask clone

pkg/surveyext/editor_manual.go
Introduced by #398
Related #318
=> fix: Use md ext to trigger syntax highlighting

internal/cmd/epic/list/list.go, internal/cmd/issue/list/list.go, internal/cmd/sprint/list/list.go, internal/cmdutil/utils.go, internal/view/epic.go, internal/view/issues.go, internal/view/sprint.go, pkg/tui/helper.go, pkg/tui/preview.go, pkg/tui/table.go
We can now customize the UI of the selected row. List of valid colors can be found [here](https://github.com/gdamore/tcell/blob/e15e96cbcae1cd93791c337294f2cb37838b8788/color.go#L846-L991). The config needs to be added manually for now and will be overwritten if you run `jira init` again.
```yaml
tui:
selection:
foreground: red
background: navy
bold: true
```
Fixes #415 #379
=> feat: Make selection highlight customizable

internal/cmd/issue/worklog/add/add.go, pkg/jira/issue.go, pkg/jira/issue_test.go
The datetime follows the format `yyyy-MM-ddTHH:mm:ss.SSSZ` expected by the Jira API (eg: `2022-01-01T09:30:00.000+0200`). This will be simplified in the subsequent PR.
```sh
jira issue worklog add ISS-1 6h --started="2022-01-01T01:02:02.000+0200"
```
=> feat: Allow to set start datetime on worklog add

internal/cmd/issue/worklog/add/add.go, internal/cmdutil/datetime.go, internal/cmdutil/datetime_test.go, pkg/jira/client.go
Relates to #453
We can now use regular date/datetime string for `started` flag in worklog add.
```sh
$ jira issue worklog add ISSUE-1 "2d 1h 30m" --started "2022-01-01 09:30:00"
$ jira issue worklog add ISSUE-1 3h --started "2022-01-01 09:30:00" --timezone "Europe/Berlin"
$ jira issue worklog add ISSUE-1 "1h 30m" --started "2022-01-01T09:30:00.000+0200"
```
=> feat: Make date time input in worklog flexible

internal/cmd/sprint/list/list.go, internal/query/issue.go, internal/query/sprint.go, pkg/jira/sprint.go, pkg/jira/sprint_test.go
Fixes #429
This PR updates `jira sprint list` to list issues from all projects if `--show-all-issues` flag is provided. By default, the command only shows issues for the given/configured project.
```sh
$ jira sprint list --show-all-issues
$ jira sprint list <sprint-id> --show-all-issues
```
=> fix: Option to show issues from all projects in sprint list

pkg/jira/create.go, pkg/jira/customfield.go, pkg/jira/edit.go
https://github.com/ankitpokhrel/jira-cli/discussions/481
=> Add support for project datatype in custom fields

README.md, internal/cmd/issue/move/move.go, pkg/jira/transition.go
This PR adds an option to set Resolution, Assignee and Comment when moving the issue. Note that these fields needs to be available in the Workflow to work, else it will be ignored.
See: https://confluence.atlassian.com/jirakb/how-to-add-a-comment-during-a-transition-779160682.html
```sh
$ jira issue move ISS-1 Done --comment "Example comment"
$ jira issue move ISS-1 Done -R Fixed
```
=> feat: Resolution, assignee & comment on issue move

internal/cmd/epic/list/list.go, internal/cmd/issue/list/list.go, internal/cmd/sprint/list/list.go, internal/view/epic.go, internal/view/issues.go, internal/view/sprint.go, pkg/tui/preview.go, pkg/tui/table.go
Allow setting the number of locked (not scrolling) columns in the issue list, epic list and sprint list.
You can do e.g.:
```
jira issues list -s~Closed --fixed-columns 2
```
And the "Type" and "KEY" columns will not disappear as you press the right arrow.
=> feat: allow setting of fixed columns in the list of issues, epics and sprints

internal/cmd/issue/create/create.go, internal/cmd/issue/edit/edit.go, internal/cmdcommon/create.go, pkg/jira/create.go, pkg/jira/edit.go
This PR removes `viper` dependency from pkg. The configuration is passed from the higher layer to keep the package more usable.
=> ehc: Remove viper dependency from pkg

.dockerignore, .github/workflows/docker.yml
The commit hash is determined [using this command](https://github.com/ankitpokhrel/jira-cli/blob/7015c54fd31a23866a7f1e7bd44fc2f3c2893fb1/Makefile#L16-L17) during the build process. This is fine and works well. However, the docker image built in the CI has invalid git commit hash. 
```sh
$ jira version
(Version="1.2.0", GitCommit="9d8a0afd75b68aa519367f93c240429117cc4090", CommitDate="2022-12-16T10:53:08+00:00", GoVersion="go1.18.3", Compiler="gc", Platform="darwin/amd64")
$ docker run -it --rm ghcr.io/ankitpokhrel/jira-cli:latest
~ # jira version
(Version="v1.2.0", GitCommit="4ae631faa92d59052320464d09e0f34842c5f971", CommitDate="2022-12-17T10:21:57+00:00", GoVersion="go1.17.11", Compiler="gc", Platform="linux/amd64")
$ git show 4ae631faa92d59052320464d09e0f34842c5f971
fatal: bad object …
```
=> fix(build): Invalid commit hash in docker image

internal/cmd/epic/create/create.go, internal/cmd/issue/create/create.go, internal/cmdcommon/create.go, pkg/jira/create.go
Instead of setting assignee in a different API call after creating an issue/epic, we can do it in a single request.
=> ehc: Make assignee operation atomic on create

internal/cmd/completion/completion.go
=> fix: Shell completion for Fish and PowerShell

internal/cmd/issue/worklog/add/add.go
=> fix: Worklog comment don't work together with prompt

internal/cmd/issue/list/list.go, internal/query/issue.go, internal/query/issue_test.go
Continuation of #559 
Related #489
Fixes #488
=> feat: Filter by multiple statuses

internal/config/generator.go
When I try to log into our JIRA instance, I get:
```
⠸ Verifying login details...
REQUEST DETAILS
------------------------------------------------------------
GET /rest/api/2/myself HTTP/1.1
Host: jira.instance
Authorization: Basic AAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaa1111111
⠙ Fetching server details...
REQUEST DETAILS
------------------------------------------------------------
GET /rest/api/2/serverInfo HTTP/1.1
Host: jira.instance
Authorization: Basic AAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaa1111111
⠹ Fetching projects...
REQUEST DETAILS
------------------------------------------------------------
GET /rest/api/2/project?expand=lead HTTP/1.1
Host: jira.instance
Authorization: Basic AAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaa1111111
⠹ Fetching boards for project 'CD'...
REQUEST DETAILS …
```
=> Try to detect if JIRA v8 server is not using the Createmeta REST endpoint

.gitignore, internal/cmd/epic/add/add.go, internal/cmd/epic/create/create.go, internal/cmd/issue/assign/assign.go, internal/cmd/issue/clone/clone.go, internal/cmd/issue/comment/add/add.go, internal/cmd/issue/create/create.go, internal/cmd/issue/edit/edit.go, internal/cmd/issue/link/link.go, internal/cmd/issue/link/remote/remote.go, internal/cmd/issue/move/move.go, internal/cmd/issue/unlink/unlink.go, internal/cmd/issue/watch/watch.go, internal/cmd/issue/worklog/add/add.go, internal/cmd/open/open.go, internal/cmd/sprint/add/add.go, internal/cmdutil/utils.go, internal/view/helper.go, internal/view/issue.go
At my company, the on-prem installation has a different API endpoint from the web client endpoint.
This change allows "browse" URLs to point to a different base URL.
https://github.com/ankitpokhrel/jira-cli/discussions/604
API server: jira-api.example.com
UI server: jira.example.com
Changes:
Consolidate all browse URLs to use common GenerateServerBrowseURL function.
Add viper config option `browse_server` to be able to modify the generated browse URLs.
Tested by adding `browse_server` to `~/.config/.jira/.config.yml`
=> Add `browse_server` setting, allows for separate api/web client endpoints.

internal/view/issue.go
=> fix: Comment author name is not always displayed

internal/cmd/epic/create/create.go, internal/cmd/issue/create/create.go, internal/cmd/issue/edit/edit.go, internal/cmdcommon/create.go, pkg/jira/create.go, pkg/jira/create_test.go, pkg/jira/edit.go, pkg/jira/types.go
@ankitpokhrel I cloned the code for fix-versions. As suggested in #587 the versions tag in the json payload could be used to set the affects version field.
I tested this for create issue only, against a cloud jira instance.
I'm not an expert in this API, (for example, in the fields.json testdata I'm unaware of this use, so not sure how/what to extend), so not in a position to say whether the PR is good or not, regardless, it should act as a starting point for this feature. 
Hope this helps,
Damian.
=> feat: affects version

README.md, api/client.go, internal/cmd/root/root.go, internal/config/generator.go, pkg/jira/client.go, pkg/jira/types.go
* Persist auth type in config file
* Update `jira init` to configure `mtls`
* Update README with instructions
Discussion: https://github.com/ankitpokhrel/jira-cli/discussions/603
```
$ jira init
? Installation type: Local
? Authentication type: mtls
? CA Certificate /home/mhatch/.certs/ca_list.pem
? MTLS Client Certificate /home/mhatch/.certs/mhatch.crt
? MTLS Client Key /home/mhatch/.certs/mhatch.key
? Link to Jira server: https://example.com/jira
? Login username: mhatch
? Default project: PROJECT
? Default board: PROJECT - Component work
```
=> feat: Add `mtls` authentication for client certificate auth

Dockerfile
Current versions of Go & Alpine introduce 5 high security vulnerabilities:
1. https://scout.docker.com/vulnerabilities/id/CVE-2023-39325
1. https://scout.docker.com/vulnerabilities/id/CVE-2023-5363
1. https://scout.docker.com/vulnerabilities/id/CVE-2023-29403
1. https://scout.docker.com/vulnerabilities/id/CVE-2023-39325
1. https://scout.docker.com/vulnerabilities/id/CVE-2023-45287
This PR bumps up Go & Alpine to their latest versions (Go 1.21 & Alpine 3.19)
=> chore(Dockerfile): bump go & alpine versions

internal/config/generator.go
I noticed the tests failing on my windows machine.
So I searched for the issue and found that created files are never closed. The fix is small and simple :)
=> Bugfix: Properly close created files

pkg/tui/helper.go, pkg/tui/helper_test.go
This is in accordance to [this comment](https://github.com/microsoft/terminal/issues/1040#issuecomment-496691842). As discussed further in the issue, in an ideal world, we wouldn't check "user agents" of terminals one-by-one, but instead would do proper feature probing like described [here](https://github.com/termstandard/colors).
But anyway: This is a good first step to enhance Windows support.
=> Consider Windows Terminal as non-dumb terminal

api/client.go, internal/cmd/issue/view/view.go, pkg/jira/issue.go, pkg/jira/issue_test.go
https://github.com/ankitpokhrel/jira-cli/issues/718
Adding `--json` flag to the `jira issue view <KEY>` command so that the tool prints the issue contents as plain JSON if the flag is set. This feature allows users to process the issue information with their programs to support various automation scenarios.
I've added an intermediate struct `printableIssue` to ensure correct null/empty values in the produced JSON, to avoid zero-values like 
```
{
...
"assignee": {
"displayName": ""
}
...
}
```
=> feat(718): issue view: raw response option

internal/cmd/epic/create/create.go
=> fix: Epic description overridden in no-input mode

internal/cmd/completion/completion.go
`/usr/local/share/zsh/site-functions` is not guaranteed to exist.  `${fpath[1]}` is a more reliable way of accessing the site-functions folder.  
https://asciinema.org/a/6I6OewMIgP1LNGKvB2virBBao
=> Improve zsh autocomplete directions

internal/cmd/issue/create/create.go, internal/cmdcommon/create.go, pkg/jira/create.go, pkg/jira/create_test.go
This PR intends to add the possibility of specifying the original estimate when creating an issue. 
* New option is called `-e, --original-estimate`
* Will set the `{ timetracking: { originalEstimate: "" }` value in the payload.
```shell 
❯ ./jira issue create --help
Create an issue in a given project with minimal information.
USAGE
jira issue create [flags]
FLAGS
-t, --type string                   Issue type
-P, --parent string                 Parent issue key can be used to attach epic to an issue.
And, this field is mandatory when creating a sub-task.
-s, --summary string                Issue summary or title
-b, --body string                   Issue description
-y, --priority string               Issue priority
-r, --reporter string               Issue reporter (username, email or …
```
=> Feature: add original estimate option to issue creation

pkg/jira/create.go, pkg/jira/create_test.go
The recent changes in PR #748 caused issues with jira-cli when used with Jira Enterprise On-Prem (now referred to as DataCenter). All requests started failing with the following error message:
```
Error:
- timetracking: Field 'timetracking' cannot be set. It is not on the appropriate screen, or unknown.
```
The issue arises because, even if the `--original-estimate` option is not specified, the timetracking field is included in the JSON query. This PR addresses the issue by ensuring that the timetracking field is only included in the JSON query if the `--original-estimate` option is set. I have tested the fix, and all tests are passing.
Please review the changes and let me know if there are any concerns.
=> fix: regression introduced by new OriginalEstimate attribute

pkg/jira/create.go
Within my cloud installation, the jira init command pulls the handle and name just fine but my administrator configured the name as "Sub-task" and the handle as "Sub-Task" which fails the equal check and causes failures with the parent key assignment. 
```
- id: "10093"
name: Sub-task
handle: Sub-Task
subtask: true
```
This PR addresses this by using an EqualFold so case insensitive matching is done for the issue type check.
=> fix: case insensitive sub-task comparison

README.md, pkg/jira/client.go
Going with `mtls` doesn't necessarily mean API token to be obsolete. Hence, this PR would make CLI incorporate API token if it is present..
The program was tested solely for our own use cases, which might differ from yours.
<sub>Lucas Zanella [lucas.zanella@mercedes-benz.com](mailto:lucas.zanella@mercedes-benz.com), Mercedes-Benz Tech Innovation GmbH, [imprint](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)</sub>
=> feat: Respect API token for `mtls` auth

internal/view/board_test.go, internal/view/epic_test.go, internal/view/helper.go, internal/view/helper_test.go, internal/view/project_test.go, internal/view/sprint.go, internal/view/sprint_test.go
The original implementation of `prepareTitle`, as well as the date ranges for sprints, used nonstandard brackets `⦗⦘` as replacements for square brackets `[]` in a hack to work around `tview` interpreting square brackets as format tags. This was causing visual problems for some powerline fonts.
The [documentation](https://pkg.go.dev/github.com/rivo/tview) for `tview` mentions that bracketed strings may be escaped by typing `[text[]` instead of `[text]`, and the package provides `tview.Escape(str)` to perform that conversion.
This change switches to using the escape function. I tried to minimize the amount of things I was touching, which also means that the expected strings in tests are a bit ugly.
=> fix: use `tview.Escape` with standard square brackets

README.md, internal/cmd/issue/comment/add/add.go, pkg/jira/issue.go, pkg/jira/issue_test.go
`issue comment add` currently only allows creating public comments.
This MR makes it so creating internal comments is possible using the `--internal` flag , useful on Jira Service Management/Desk.
=> Allow adding internal comment on JSD

internal/cmd/issue/list/list.go
Adds the ability to provide an optional positional arg to search for text in issues.
It functions the same as searching via the search bar in the Jira web UI and is appended to any raw JQL query provided in the "-q" flag.
I'm also open to refactoring this into its own subcommand, if that's preferable. I know this is already possible with the "-q" flag, this is just intended to be a nice convenience function.
=> feat: add easy issue search to list cmd

README.md, internal/cmd/root/root.go
Solves #713 #434
This pull request introduces a new environment variable, `JIRA_CONFIG_FILE`, which allows users to specify the path to the configuration file.
A common use case is working with multiple Jira servers across different projects simultaneously. In such scenarios, it’s helpful to maintain separate configuration files to avoid conflicts, especially with credentials.
While the solution proposed in #434 — using the `--config/-c` flag — is a valid option, it requires specifying the argument manually for every command. This approach is prone to errors and adds complexity when writing automated scripts.
Similarly, the solution proposed in #713 — relying on the `XDG_CONFIG_HOME` environment variable — affects a broader range of tools beyond `jira-cli`, which may lead to unintended …
=> Add support for environment variable to specify config file path

internal/config/generator.go
Valid usernames can be only two characters.  Don't exclude these users from using this tool!
=> fix: usernames can be 2 chars

api/client.go, internal/cmd/epic/list/list.go, internal/cmd/issue/list/list.go, internal/cmd/sprint/list/list.go, internal/view/epic.go, internal/view/epic_test.go, internal/view/issues.go, internal/view/issues_test.go, pkg/jira/epic_test.go, pkg/jira/search.go, pkg/jira/search_test.go, pkg/jira/sprint_test.go, pkg/jira/testdata/search.json
Fixes #891 
> This PR is a work in progress
> [!IMPORTANT]
>  - The [new API](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-search/#api-rest-api-3-search-jql-get) does not return the total number of entries anymore, so the total issue count is no longer displayed in the search results.
>  - Consequently, the `startAt` parameter in the new API is unsupported. Therefore, the `from` part of the `--paginate=<from>:<limit>` flag is effectively ignored. Users can still paginate using the maxResults parameter (e.g., --paginate=10).
=> fix: Update deprecated endpoint
