ankitpokhrel/jira-cli

README.md, internal/cmd/epic/epic.go, internal/cmd/epic/list/list.go, internal/cmd/issue/issue.go, internal/cmd/issue/list/list.go, internal/cmd/sprint/list/list.go, internal/cmd/sprint/sprint.go
Move to subcommand to list issues, epics and sprints. This will allow us to add other subcommands as mentioned below.
```
$ jira issue list
$ jira issue create
$ jira issue view
...
```
=> chore: Move to subcommand

go.mod, go.sum, internal/cmd/issue/create/create.go, pkg/surveyext/editor.go, pkg/surveyext/editor_manual.go
=> feat: Interactive create prompt

.golangci.yml, internal/cmd/issue/move/move.go
=> feat: Interactive move command

internal/cmd/init/init.go, internal/config/generator.go, pkg/jira/createmeta.go, pkg/jira/createmeta_test.go, pkg/jira/testdata/createmeta.json, pkg/jira/types.go
=> feat: Add epic field name in config during init

internal/view/epic.go, internal/view/helper.go, internal/view/issue.go, internal/view/issues.go, internal/view/sprint.go, pkg/tui/helper.go, pkg/tui/preview.go, pkg/tui/table.go
Pressing `v` will open issue details.
A key event is lost when switching the screen, see: https://github.com/gdamore/tcell/issues/194
https://user-images.githubusercontent.com/2364546/103306049-ed865980-4a0c-11eb-8950-048a01ada165.mov
=> feat: Issue view mode

go.mod, go.sum, internal/cmd/board/board.go, internal/cmd/epic/create/create.go, internal/cmd/epic/epic.go, internal/cmd/epic/list/list.go, internal/cmd/issue/create/create.go, internal/cmd/issue/issue.go, internal/cmd/issue/list/list.go, internal/cmd/issue/move/move.go, internal/cmd/issue/view/view.go, internal/cmd/open/open.go, internal/cmd/project/project.go, internal/cmd/root/help.go, internal/cmd/root/root.go, internal/cmd/sprint/list/list.go, internal/cmd/sprint/sprint.go
=> feat: Improve help page

internal/view/epic.go, internal/view/issues.go, internal/view/sprint.go, pkg/tui/helper.go, pkg/tui/preview.go, pkg/tui/primitive/modal.go, pkg/tui/table.go
=> feat: Show loader on same screen when switching to view mode

internal/cmd/issue/create/create.go, internal/cmd/issue/move/move.go, internal/config/generator.go, pkg/jira/createmeta.go, pkg/jira/createmeta_test.go, pkg/jira/testdata/createmeta.json, pkg/jira/types.go
Updates config. Re-run `jira init`.
=> feat(cmd): Show available issue types in dropdown during creation

internal/cmd/issue/create/create.go
Instead of submitting directly, confirm with user as a final step.
=> feat: Ask before submitting the issue

internal/cmd/epic/create/create.go, internal/cmd/issue/create/create.go, internal/cmdcommon/create.go, internal/cmdcommon/doc.go
https://user-images.githubusercontent.com/2364546/105750808-77124400-5f45-11eb-8831-c6ac9fcb1aa8.mov
=> feat(create): Ability to add metadata when using interactive UI

README.md, internal/cmd/issue/list/list.go, pkg/jql/jql.go, pkg/jql/jql_test.go
List issues whose status is not done and is created before 6 months and is assigned to someone
```sh
$ jira issue list -s~Done --created-before -24w -a~x
```
=> feat: Filter by NOT operator

README.md, internal/cmd/root/help.go
This PR:
- Adds `ALIASES` section in help.
- Updates README.
=> chore: Docs improvement

README.md, internal/cmd/issue/issue.go, internal/cmd/issue/link/link.go, pkg/jira/issue.go, pkg/jira/issue_test.go, pkg/jira/testdata/issue-link-types.json, pkg/jira/types.go
```sh
$ jira issue link
$ jira issue link ISSUE-1 ISSUE-2 Blocks
```
=> feat: Ability to link issues

internal/cmd/issue/link/link.go
```sh
$ jira issue link ANK-2 ANK-5 Block
✗ Invalid issue link type "Block"
Available issue link types are: 'Blocks', 'Cloners', 'Duplicate', 'Relates'
```
=> feat: Add issue link type validation

README.md
Update Readme to match with PR https://github.com/ankitpokhrel/jira-cli/pull/107 that updates `EPIC` related commands.
=> chore: update doc to match with PR #107

go.mod
```sh
go mod edit -go=1.16
```
=> chore: Upgrade to go1.16

go.mod, go.sum
Fixes #99 with https://github.com/kentaro-m/blackfriday-confluence/pull/20
=> fix: Line feed issue when writing description

internal/cmd/board/board.go, internal/cmd/epic/add/add.go, internal/cmd/epic/create/create.go, internal/cmd/epic/list/list.go, internal/cmd/epic/remove/remove.go, internal/cmd/init/init.go, internal/cmd/issue/assign/assign.go, internal/cmd/issue/clone/clone.go, internal/cmd/issue/comment/add/add.go, internal/cmd/issue/create/create.go, internal/cmd/issue/link/link.go, internal/cmd/issue/list/list.go, internal/cmd/issue/move/move.go, internal/cmd/project/project.go, internal/cmd/root/root.go, internal/cmd/sprint/list/list.go, internal/cmdutil/utils.go
- Refactor success message
- Refactor failure message
=> chore: Refactor success and failure messages

internal/config/generator.go
=> fix: Epic field is linked differently in v7

README.md, internal/cmd/epic/add/add.go, internal/cmdutil/utils.go, internal/cmdutil/utils_test.go, pkg/jira/client.go, pkg/jira/edit.go
=> fix: Make epic add work in next-gen project

internal/view/epic.go, internal/view/helper.go, internal/view/issues.go, internal/view/sprint.go
=> fix: Segmentation fault on view

.goreleaser.yml, README.md, internal/cmd/sprint/list/list.go, internal/version/version.go
- doc: Fix minor discrepancies
- build: Remove unnecessary quotation
- build: Use "dev" as default version
=> Doc and build improvements

internal/cmd/board/board.go, internal/config/generator.go
=> fix: Allow config generations even when no boards

.gitignore, internal/view/epic.go, internal/view/issue.go, internal/view/issue_test.go, internal/view/issues.go, internal/view/sprint.go
This PR:
- Decouples issue view logic to some extent.
- Beautifies issue view presentation.
=> chore: Refactor view so that it can be parsed in fragments

README.md, internal/cmd/issue/view/view.go, internal/view/epic.go, internal/view/issue.go, internal/view/issue_test.go, internal/view/issues.go, internal/view/sprint.go, pkg/jira/issue.go, pkg/jira/types.go
This PR modifies view layout to show latest comment on `jira issue view` (if any).
=> feat: Show latest comment when viewing

pkg/md/jirawiki/parser.go, pkg/md/jirawiki/parser_test.go
=> fix: Off by one error in wiki parser

README.md, internal/cmd/issue/create/create.go, internal/config/generator.go, internal/view/epic_test.go, internal/view/issue_test.go, internal/view/issues_test.go, internal/view/sprint_test.go, pkg/jira/epic_test.go, pkg/jira/issue_test.go, pkg/jira/search_test.go, pkg/jira/sprint_test.go, pkg/jira/types.go
=> fix: Language support for Jira cloud

README.md, internal/cmd/issue/comment/add/add.go, internal/cmd/issue/create/create.go
=> chore: Update docs

.gitignore, Makefile
* edit .gitignore: add /.gocache
* edit Makefile:
* add .PHONY targets clean and distclean
* export GOCACHE with default
=> fix #237: add targets: clean, distclean

go.mod, go.sum, internal/cmd/open/open.go, internal/cmdutil/utils.go, internal/view/helper.go, pkg/browser/browser.go, pkg/browser/browser_test.go
=> fix: Respect BROWSER env

internal/cmd/init/init.go, internal/cmd/root/root.go, internal/config/generator.go
=> fix: Config generation issue

internal/view/helper.go
=> fix: Respect GLAMOUR_STYLE env on issue view

internal/cmd/issue/create/create.go, internal/cmdutil/utils.go, internal/cmdutil/utils_test.go, pkg/jira/create.go
=> fix: Get subtask handle from config

internal/config/generator.go, pkg/jira/board.go, pkg/jira/board_test.go
=> feat: Add search option for boards on jira init

README.md, api/client.go, internal/config/generator.go, pkg/jira/client.go, pkg/jira/me.go, pkg/jira/types.go
This PR extends the initial work done by @marek-veber to support PAT.
Fixes #312 #323
Closes #313 #268
=> feat: Support auth with personal access tokens

pkg/md/jirawiki/parser.go, pkg/md/jirawiki/parser_test.go
This PR fixes out out index issue when parsing empty sub-list.
=> fix: Panic on empty sub-list

README.md, internal/cmd/epic/list/list.go, internal/cmd/issue/list/list.go, internal/cmd/sprint/list/list.go, internal/view/issues.go, pkg/tui/table.go
This PR add refreshing behaviour when the `<C-R>` or `F5` key is pressed when viewing issues list
relating to #292 but with no interval implemented
=> feat: support refresh for issues list

README.md, internal/cmd/issue/delete/delete.go, internal/cmd/issue/issue.go, pkg/jira/client.go, pkg/jira/client_test.go, pkg/jira/delete.go, pkg/jira/delete_test.go
=> feat: Ability to delete issue

internal/cmd/issue/assign/assign.go, internal/cmd/issue/edit/edit.go, pkg/jira/edit.go, pkg/jira/testdata/users.json, pkg/jira/types.go, pkg/jira/user_test.go
=> fix: Issue with assigning user

internal/view/issue.go
=> fix: OOM bug on issue view

internal/cmd/issue/edit/edit.go, pkg/jira/types.go
=> fix: Assign parent key as is on edit

api/client.go, go.mod, go.sum, internal/cmd/root/root.go
Addresses #247 
_Notice: Only tested on macOS._
=> Add support for OS keyrings/-chains

api/client.go, internal/cmd/epic/list/list.go, internal/cmd/issue/list/list.go, internal/cmd/sprint/list/list.go, internal/query/issue.go, internal/query/issue_test.go, internal/query/sprint.go, internal/query/sprint_test.go, pkg/jira/epic.go, pkg/jira/epic_test.go, pkg/jira/search.go, pkg/jira/search_test.go, pkg/jira/sprint.go, pkg/jira/sprint_test.go
=> fix!: Replace limit flag with paginate

internal/cmd/issue/issue.go, internal/cmd/issue/unlink/unlink.go, internal/view/issue_test.go, pkg/jira/issue.go, pkg/jira/issue_test.go, pkg/jira/testdata/issue.json, pkg/jira/types.go
=> feat: Add issues unlink command

internal/cmd/epic/create/create.go, internal/cmd/issue/create/create.go
=> feat: Allow to set custom fields on epic create

internal/cmd/issue/edit/edit.go
This is a breaking change. Subsequent PRs will allow ways to remove components/labels/fixVersions on edit.
=> fix!: Append components on edit instead of overriding

pkg/jira/edit.go
We can use minus `-` to remove components when editing the issue.
```sh
jira issue edit 35 --component -BE --component mobile
```
=> feat: Allow removing component on edit

pkg/jira/user.go, pkg/jira/user_test.go
=> fix: Issue with query param in user assignment

internal/view/issue.go, internal/view/issue_test.go, pkg/jira/types.go
=> feat: Show subtasks in issue view

.dockerignore, .github/workflows/docker.yml
=> ci: Add workflow to publish docker image to ghcr

internal/cmd/issue/edit/edit.go
=> fix: editing issue with custom field in non interactive mode

internal/cmd/issue/assign/assign.go
=> fix: Issue with default assignee and unassign from tui

README.md, internal/cmd/issue/issue.go, internal/cmd/issue/worklog/add/add.go, internal/cmd/issue/worklog/worklog.go, pkg/jira/issue.go
Relates to #181
```sh
$ jira issue worklog add ISSUE-42 "2d 3h 30m" --comment "Some comment"
```
=> feat: Ability to add worklog

internal/config/generator.go
=> fix: Issue with insecure TLS config

internal/cmd/root/root.go, internal/cmd/serverinfo/serverinfo.go, internal/view/serverinfo.go, internal/view/serverinfo_test.go, pkg/jira/serverinfo.go, pkg/jira/serverinfo_test.go, pkg/jira/testdata/serverinfo.json
```sh
$ jira serverinfo
SERVER INFO
-----------
Version:         1001.0.0-SNAPSHOT
Build Number:    100204
Deployment Type: Cloud
Default Locale:  en_US
```
=> feat: Add serverinfo command

internal/cmd/root/help.go, internal/cmd/root/root.go
=> doc: Add link to project in help

README.md
=> doc: Add Nix package

internal/cmd/completion/completion.go
=> doc: Update help for completion cmd

.github/workflows/docker.yml
=> ci: Multi-arch docker image

internal/query/issue.go, pkg/jql/jql.go, pkg/jql/jql_test.go
you can now do e.g.
```
jira issues list -l~cna -l~web-rca -l~status-board -l~app-interface
```
to list issues that have none of the labels above
=> feat: filter issues by the absence of label(s)

internal/view/fields.go, internal/view/helper.go, internal/view/issues.go, internal/view/issues_test.go, internal/view/sprint.go, internal/view/sprint_test.go
feat: add labels to the issue listing
add the ability to display issue labels in the issue list
```
jira issue list -s~Closed --columns KEY,TYPE,SUMMARY,STATUS,ASSIGNEE,CREATED,labels
```
=> feat: add labels to the issue listing

internal/config/generator.go, pkg/jira/client.go
=> fix: Make board selection optional

internal/view/issues.go, internal/view/sprint.go, pkg/tui/helper.go, pkg/tui/helper_test.go
=> fix: Improve support for pager

pkg/surveyext/editor.go
=> fix: Respect editor env vars in Windows

internal/cmd/epic/create/create.go, internal/cmd/issue/create/create.go, internal/cmd/issue/edit/edit.go, internal/cmdcommon/create.go
=> feat: Add warning for invalid custom field

go.mod, internal/cmd/epic/list/list.go, internal/cmd/sprint/list/list.go, internal/view/issue.go, internal/view/issues.go, internal/view/sprint.go, pkg/tui/helper.go
=> ehc: Auto fallback to plain output on notty

internal/cmd/epic/create/create.go, internal/cmd/issue/create/create.go, internal/cmdcommon/create.go, pkg/jira/create.go
=> feat: Allow to set reporter on issue create

README.md, internal/view/issues.go, pkg/tui/helper.go, pkg/tui/primitive/actionmodal.go, pkg/tui/table.go
Relates to #403 
With this change, pressing `m` in the TUI will let us quickly transition the issue status.
=> feat(tui): Allow issue transition from the ui

README.md, internal/view/helper.go, internal/view/issues.go, pkg/tui/primitive/infomodal.go, pkg/tui/table.go
Pressing `?` in the list page will show the help window
=> feat: Add help page

README.md, pkg/tui/helper.go, pkg/tui/helper_test.go
=> ehc: Improve PAGER selection

api/client.go, internal/cmd/issue/issue.go, internal/cmd/issue/watch/watch.go, pkg/jira/issue.go, pkg/jira/issue_test.go
Continuation of #581 
Related #452 
Original work by @abhishekbiyala
=> feat: Support for adding watcher to Issue

internal/config/generator.go, internal/config/generator_test.go
=> fix: Issue with -c flag on config generation

internal/config/generator.go
=> fix: Issue with value assignment in init

pkg/jira/create.go
Fixes #555 
Fixes #586 
Fixes #605
=> fix: Issue with epic field on create

internal/cmd/epic/create/create.go, internal/cmd/issue/create/create.go
=> fix: Issue with no-input on create

internal/cmd/epic/list/list.go, internal/cmd/issue/list/list.go, internal/cmd/sprint/list/list.go, internal/config/generator.go, internal/view/epic.go, internal/view/helper.go, internal/view/helper_test.go, internal/view/issues.go, internal/view/sprint.go, pkg/jira/me.go
=> fix: Respect jira timezone

README.md, api/client.go, internal/cmd/init/init.go, internal/config/generator.go, pkg/jira/client.go
=> fix: Skip auth type prompt if already set

pkg/jira/sprint.go, pkg/jira/sprint_test.go, pkg/jira/testdata/sprint-get.json
=> chore: Add tests for sprint close

.golangci.yml, Makefile, internal/cmd/root/help.go, internal/cmdutil/datetime.go, internal/cmdutil/utils.go, internal/config/generator.go, internal/view/board.go, internal/view/helper.go, internal/view/project.go, internal/view/serverinfo.go, pkg/tui/primitive/actionmodal.go, pkg/tui/primitive/infomodal.go
=> Fix lint issues

.goreleaser.yml
I can't thank you enough for your work here.  Using the CLI makes me so happy.
closes #651.
=> add shell completion to brew install; closes #651

internal/view/helper.go
=> fix: Tag stripping in plain mode

internal/cmd/issue/list/list.go, internal/cmd/issue/view/view.go, internal/view/issue.go, internal/view/issues.go
=> feat: Support num comments in issue list cmd
